export const movieCredits = {
  id: 573436,
  cast: [
    {
      adult: false,
      gender: 2,
      id: 12796,
      known_for_department: "Acting",
      name: "Johnny Strong",
      original_name: "Johnny Strong",
      popularity: 17.796,
      profile_path: "/zMe5hbmaMA5Jr6uVwtojusANaCg.jpg",
      cast_id: 3,
      character: "Master Chief Richard Mirko",
      credit_id: "63ca1f6268afd600c954096b",
      order: 0,
    },
    {
      adult: false,
      gender: 0,
      id: 3882182,
      known_for_department: "Acting",
      name: "Athena Durner",
      original_name: "Athena Durner",
      popularity: 1.529,
      profile_path: "/iQk9N5WOLvflt9Yo7NXdtIMcFn3.jpg",
      cast_id: 4,
      character: "Zoe Walters",
      credit_id: "63ca1f8fed96bc009bf622f3",
      order: 1,
    },
    {
      adult: false,
      gender: 2,
      id: 1431483,
      known_for_department: "Acting",
      name: "Raj Kala",
      original_name: "Raj Kala",
      popularity: 3.016,
      profile_path: null,
      cast_id: 5,
      character: "Radam",
      credit_id: "63ca1fe5bb070d00c8a0f962",
      order: 2,
    },
    {
      adult: false,
      gender: 0,
      id: 3882183,
      known_for_department: "Acting",
      name: "James Sherrill",
      original_name: "James Sherrill",
      popularity: 0.6,
      profile_path: null,
      cast_id: 6,
      character: "Petty Officer James 'G' Wiliker",
      credit_id: "63ca2013ed96bc00838d6e12",
      order: 3,
    },
    {
      adult: false,
      gender: 0,
      id: 3882184,
      known_for_department: "Acting",
      name: "Michael Sauers",
      original_name: "Michael Sauers",
      popularity: 1.4,
      profile_path: null,
      cast_id: 7,
      character: "Chief Petty Officer Mike Miller",
      credit_id: "63ca203ded96bc009bf62343",
      order: 4,
    },
  ],
  crew: [
    {
      adult: false,
      gender: 2,
      id: 12796,
      known_for_department: "Acting",
      name: "Johnny Strong",
      original_name: "Johnny Strong",
      popularity: 17.796,
      profile_path: "/zMe5hbmaMA5Jr6uVwtojusANaCg.jpg",
      credit_id: "63ca1f19ed96bc00c394b0a5",
      department: "Directing",
      job: "Director",
    },
    {
      adult: false,
      gender: 2,
      id: 12796,
      known_for_department: "Acting",
      name: "Johnny Strong",
      original_name: "Johnny Strong",
      popularity: 17.796,
      profile_path: "/zMe5hbmaMA5Jr6uVwtojusANaCg.jpg",
      credit_id: "644c8f3f51a64e08fcddbe8d",
      department: "Production",
      job: "Producer",
    },
    {
      adult: false,
      gender: 2,
      id: 12796,
      known_for_department: "Acting",
      name: "Johnny Strong",
      original_name: "Johnny Strong",
      popularity: 17.796,
      profile_path: "/zMe5hbmaMA5Jr6uVwtojusANaCg.jpg",
      credit_id: "644c9a85e2ff32074ed28f2f",
      department: "Sound",
      job: "Original Music Composer",
    },
    {
      adult: false,
      gender: 2,
      id: 12796,
      known_for_department: "Acting",
      name: "Johnny Strong",
      original_name: "Johnny Strong",
      popularity: 17.796,
      profile_path: "/zMe5hbmaMA5Jr6uVwtojusANaCg.jpg",
      credit_id: "644c8f10e2ff32074ed28999",
      department: "Writing",
      job: "Writer",
    },
    {
      adult: false,
      gender: 2,
      id: 228177,
      known_for_department: "Directing",
      name: "William Kaufman",
      original_name: "William Kaufman",
      popularity: 3.786,
      profile_path: "/s5hjF7hxSnVTlzSSla4w0mQa2DZ.jpg",
      credit_id: "63ca1f37006b0100967876a5",
      department: "Directing",
      job: "Director",
    },
    {
      adult: false,
      gender: 2,
      id: 228177,
      known_for_department: "Directing",
      name: "William Kaufman",
      original_name: "William Kaufman",
      popularity: 3.786,
      profile_path: "/s5hjF7hxSnVTlzSSla4w0mQa2DZ.jpg",
      credit_id: "644c8f27726fb127a2068060",
      department: "Writing",
      job: "Writer",
    },
    {
      adult: false,
      gender: 0,
      id: 2690017,
      known_for_department: "Visual Effects",
      name: "Nate Hardy",
      original_name: "Nate Hardy",
      popularity: 0.98,
      profile_path: null,
      credit_id: "644c9846e2ff320500d28e66",
      department: "Visual Effects",
      job: "Visual Effects Supervisor",
    },
    {
      adult: false,
      gender: 0,
      id: 4034546,
      known_for_department: "Production",
      name: "Nicole Kaufman",
      original_name: "Nicole Kaufman",
      popularity: 0.6,
      profile_path: null,
      credit_id: "644c8f4ce2ff320953d28bca",
      department: "Production",
      job: "Producer",
    },
    {
      adult: false,
      gender: 0,
      id: 4034562,
      known_for_department: "Production",
      name: "Paul Reichelt",
      original_name: "Paul Reichelt",
      popularity: 0.6,
      profile_path: null,
      credit_id: "644c9883596a912cec58429a",
      department: "Production",
      job: "Executive Producer",
    },
    {
      adult: false,
      gender: 0,
      id: 4034563,
      known_for_department: "Production",
      name: "Dan Dearing",
      original_name: "Dan Dearing",
      popularity: 0.6,
      profile_path: null,
      credit_id: "644c98ae2d372102fb01221f",
      department: "Production",
      job: "Associate Producer",
    },
    {
      adult: false,
      gender: 0,
      id: 4034564,
      known_for_department: "Production",
      name: "Martin Buzbee",
      original_name: "Martin Buzbee",
      popularity: 0.6,
      profile_path: null,
      credit_id: "644c98d7726fb127a2068f00",
      department: "Production",
      job: "Associate Producer",
    },
    {
      adult: false,
      gender: 0,
      id: 4034565,
      known_for_department: "Production",
      name: "Rebecca Schiffhauer",
      original_name: "Rebecca Schiffhauer",
      popularity: 0.6,
      profile_path: null,
      credit_id: "644c98e80c1255264e7b3870",
      department: "Production",
      job: "Associate Producer",
    },
    {
      adult: false,
      gender: 0,
      id: 4034566,
      known_for_department: "Production",
      name: "Mitch Wollebaek",
      original_name: "Mitch Wollebaek",
      popularity: 0.6,
      profile_path: null,
      credit_id: "644c99380c1255264e7b38d0",
      department: "Production",
      job: "Associate Producer",
    },
    {
      adult: false,
      gender: 0,
      id: 4034567,
      known_for_department: "Production",
      name: "Operator Films",
      original_name: "Operator Films",
      popularity: 0.6,
      profile_path: null,
      credit_id: "644c998f726fb127a2068ffb",
      department: "Production",
      job: "Producer",
    },
  ],
};
